image: gradle:latest

stages:
  - build
  - test
  - deploy

variables:
  GRADLE_USER_HOME: "`pwd`/.gradle"
  MC_VERSION: "1.17"

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    # Install Paper to local Maven repo
    - "apt install jq maven"
    - "build=$(curl https://papermc.io/api/v2/projects/paper/versions/${MC_VERSION} | jq '.builds[-1]')"
    - "curl -o paperclip.jar https://papermc.io/api/v2/projects/paper/versions/${MC_VERSION}/builds/${build}/downloads/paper-${MC_VERSION}-${build}.jar"
    - "java -Dpaperclip.install=true -jar paperclip.jar"
    # Build project
    - "./gradlew assemble"
  artifacts:
    paths:
      - "*/build/libs/*.jar"
    expire_in: 1 week

test:
  stage: test
  script:
    - "./gradlew check"

deploy:
  stage: deploy
  script:
    - "./gradlew publish"
  only:
    - master
