image: gradle:jdk16

stages:
  - build
  - test
  - deploy
  - pages

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GRADLE_USER_HOME: "${CI_PROJECT_DIR}/.gradle"
  MC_VERSION: "1.17.1"

build:
  stage: build
  script:
    # Install libraries
    - "mkdir -p libraries && cd libraries"
    - "mkdir -p gradle-cache"
    # -> Paper
    - "git clone https://github.com/papermc/paper"
    - "cd paper"
    # --> Pull gradle cache
    - "mv ../gradle-cache/paper .gradle || true"
    # --> Install
    - "git config --global user.email 'ci'"
    - "git config --global user.name 'ci'"
    - "gradle applyPatches"
    - "gradle publishToMavenLocal"
    # --> Cache gradle
    - "mv .gradle ../gradle-cache/paper"

    # Return
    - "cd ../.."
    # Build project
    - "gradle --build-cache assemble"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull-push
    paths:
      - "*/build"
      - ".gradle"
      - "libraries/gradle-cache"
  artifacts:
    paths:
      - ".gradle"
      - "*/build/libs/*.jar"
    expire_in: 1 week

test:
  stage: test
  script:
    - "gradle check"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - "*/build"
      - ".gradle"

deploy:
  stage: deploy
  script:
    - "gradle publish"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - "*/build"
      - ".gradle"
  only:
    - master

pages:
  stage: pages
  script:
    - "gradle javadoc"
    - "mv src/site public"
    - "mkdir -p public/javadoc"
    - "mv core/build/docs/javadoc public/javadoc/core"
    - "mv paper/build/docs/javadoc public/javadoc/paper"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - "*/build"
      - ".gradle"
  only:
    - master
