image: "maven:latest"

cache:
  paths:
    - "maven.repository/"

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=maven.repository"

build:
  script:
    - "mvn package -B"
  artifacts:
    paths:
      - "*/target"
