image: gradle:jdk16

stages:
  - build
  - test

variables:
  GRADLE_USER_HOME: `pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    # Install Paper to local Maven repo
    - "apt-get install jq"
    - "version='1.17'"
    - "build=$(curl https://papermc.io/api/v2/projects/paper/versions/${version} | jq '.builds[-1]')"
    - "curl --output paperclip.jar https://papermc.io/api/v2/projects/paper/versions/${version}/builds/${build}/downloads/paper-${version}-${build}.jar"
    - "java -Dpaperclip.install=true -jar paperclip.jar"
    # Build project
    - "./gradlew assemble"
  artifacts:
    paths:
      - "*/build/libs/*.jar"
    expire_in: 1 week

test:
  stage: test
  script:
    - "./gradlew check"

deploy:
  stage: deploy
  script:
    - "./gradlew publish"
  only:
    - master
