image: gradle:jdk16

stages:
  - build
  - test
  - deploy

variables:
  GRADLE_USER_HOME: "`pwd`/.gradle"

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    # Install Paper to local Maven repo
    - "mkdir libraries && cd libraries"
    - "git clone https://github.com/papermc/paper && cd paper"
    - "./gradlew applyPatches publishToMavenLocal"
    - "cd ../.."
    # Build project
    - "./gradlew assemble"
  artifacts:
    paths:
      - "*/build/libs/*.jar"
    expire_in: 1 week

test:
  stage: test
  script:
    - "./gradlew check"

deploy:
  stage: deploy
  script:
    - "./gradlew publish"
  only:
    - master
