image: alpine:latest

stages:
  - build
  - deploy

variables:
  GRADLE_USER_HOME: "${CI_PROJECT_DIR}/.gradle"

build:
  stage: build
  script:
    - "apk add --no-cache git openjdk17"
    - "./gradlew --build-cache build publish"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull-push
    paths:
      - "*/build"
      - "*/.gradle"
  artifacts:
    paths:
      - "*/build/libs/*.jar"
    expire_in: 1 week

pages:
  stage: deploy
  script:
    - "./gradlew javadoc"
    - "mv src/site public"
    - "mkdir -p public/javadoc"
    - "mv minecommons-core/build/docs/javadoc public/javadoc/minecommons-core"
    - "mv minecommons-paper/build/docs/javadoc public/javadoc/minecommons-paper"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - "*/build"
      - "*/.gradle"
  artifacts:
    paths:
      - "public"
  only:
    - master
