image: gradle:jdk16

stages:
  - build
  - test
  - publish
  - deploy

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dmaven.repo.local=${CI_PROJECT_DIR}/.m2/repository"
  GRADLE_USER_HOME: "${CI_PROJECT_DIR}/.gradle"
  MC_VERSION: "1.17.1"

build:
  stage: build
  script:
    # Install libraries
    - "mkdir -p libraries && cd libraries"
    # Paper
    - "git clone https://github.com/papermc/paper || true"
    - "cd paper"
    - "git pull"
    - "git config --global user.email 'ci'"
    - "git config --global user.name 'ci'"
    - "gradle applyPatches"
    - "gradle publishToMavenLocal"

    # Build project
    - "cd ../.."
    - "gradle --build-cache assemble"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull-push
    paths:
      - "*/build"
      - ".gradle"
      - "libraries"
      - ".m2/repository"
  artifacts:
    paths:
      - ".gradle"
      - "*/build/libs/*.jar"
    expire_in: 1 week

test:
  stage: test
  script:
    - "gradle check"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - "*/build"
      - ".gradle"
      - ".m2/repository"

publish:
  stage: publish
  script:
    - "gradle publish"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - "*/build"
      - ".gradle"
      - ".m2/repository"
  only:
    - master

deploy:
  stage: deploy
  script:
    - "gradle javadoc"
    - "mv src/site public"
    - "mkdir -p public/javadoc"
    - "mv core/build/docs/javadoc public/javadoc/core"
    - "mv paper/build/docs/javadoc public/javadoc/paper"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - "*/build"
      - ".gradle"
      - ".m2/repository"
  only:
    - master
