image: "maven:latest"

cache:
  paths:
    - "maven.repository/"

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=maven.repository"

build:
  script:
    - "microdnf update && microdnf install jq"
    - "version='1.16.5'"
    - "build=$(curl https://papermc.io/api/v2/projects/paper/versions/1.16.5 | jq '.builds[-1]')"
    - "curl --output paperclip.jar https://papermc.io/api/v2/projects/paper/versions/1.16.5/builds/${build}/downloads/paper-${version}-${build}.jar"
    - "java -Dpaperclip.install=true -jar paperclip.jar"
    - "mvn package -B"
  artifacts:
    paths:
      - "*/target"
