[versions]

minecraft = "1.19.3"
kotlin = "1.8.0"
kotlinxCoroutines = "1.6.4"
adventure = "4.11.0"
glossa = "0.6.0"
configurate = "4.1.2"
bstats = "3.0.0"
cloud = "1.8.0"
packetEvents = "2.0-SNAPSHOT"

[libraries]

kotlinxCoroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }

adventureApi = { group = "net.kyori", name = "adventure-api", version.ref = "adventure" }
adventureExtraKotlin = { group = "net.kyori", name = "adventure-extra-kotlin", version.ref = "adventure" }
adventureSerializerConfigurate = { group = "net.kyori", name = "adventure-serializer-configurate4", version.ref = "adventure" }

glossaCore = { group = "io.gitlab.aecsocket", name = "glossa-core", version.ref = "glossa" }
glossaAdventure = { group = "io.gitlab.aecsocket", name = "glossa-adventure", version.ref = "glossa" }

configurateCore = { group = "org.spongepowered", name = "configurate-core", version.ref = "configurate" }
configurateExtraKotlin = { group = "org.spongepowered", name = "configurate-extra-kotlin", version.ref = "configurate" }
configurateHocon = { group = "org.spongepowered", name = "configurate-hocon", version.ref = "configurate" }

bstatsBukkit = { group = "org.bstats", name = "bstats-bukkit", version.ref = "bstats" }

cloudCore = { group = "cloud.commandframework", name = "cloud-core", version.ref = "cloud" }
cloudPaper = { group = "cloud.commandframework", name = "cloud-paper", version.ref = "cloud" }
cloudMinecraftExtras = { group = "cloud.commandframework", name = "cloud-minecraft-extras", version.ref = "cloud" }

packetEventsApi = { group = "com.github.retrooper.packetevents", name = "api", version.ref = "packetEvents" }
packetEventsSpigot = { group = "com.github.retrooper.packetevents", name = "spigot", version.ref = "packetEvents" }
