[versions]

minecraft = "1.18.2"

adventure = "4.11.0"
glossa = "0.3.4"
configurate = "4.1.2"
cloud = "1.6.2"
packetEvents = "2.0-SNAPSHOT"

[libraries]

adventureApi = { group = "net.kyori", name = "adventure-api", version.ref = "adventure" }
adventureTextLoggerSlf4j = { group = "net.kyori", name = "adventure-text-logger-slf4j", version.ref = "adventure" }
adventureExtraKotlin = { group = "net.kyori", name = "adventure-extra-kotlin", version.ref = "adventure" }

glossaAdventure = { group = "com.github.aecsocket.glossa", name = "glossa-adventure", version.ref = "glossa" }
glossaConfigurate = { group = "com.github.aecsocket.glossa", name = "glossa-configurate", version.ref = "glossa" }

configurateCore = { group = "org.spongepowered", name = "configurate-core", version.ref = "configurate" }
configurateExtraKotlin = { group = "org.spongepowered", name = "configurate-extra-kotlin", version.ref = "configurate" }
configurateHocon = { group = "org.spongepowered", name = "configurate-hocon", version.ref = "configurate" }

cloudCore = { group = "cloud.commandframework", name = "cloud-core", version.ref = "cloud" }
cloudPaper = { group = "cloud.commandframework", name = "cloud-paper", version.ref = "cloud" }
cloudMinecraftExtras = { group = "cloud.commandframework", name = "cloud-minecraft-extras", version.ref = "cloud" }

packetEventsApi = { group = "com.github.retrooper.packetevents", name = "api", version.ref = "packetEvents" }
