[versions]

junit = "5.7.2"
minecraft = "1.18.1"

guava = "31.0.1-jre"
checkerQual = "3.18.0"
geantyRef = "1.3.11"
configurate = "4.1.2"
openCsv = "2.3"
interfaces = "1.0.0-SNAPSHOT"
adventure = "4.9.3"
adventureMiniMessage = "4.1.0-SNAPSHOT"

cloud = "1.6.1"
protocolLib = "4.8.0-SNAPSHOT"

[libraries]

jupiterApi = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
jupiterEngine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }

guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
checkerQual = { group = "org.checkerframework", name = "checker-qual", version.ref = "checkerQual" }
geantyRef = { group = "io.leangen.geantyref", name = "geantyref", version.ref = "geantyRef" }
configurate = { group = "org.spongepowered", name = "configurate-hocon", version.ref = "configurate" }
openCsv = { group = "net.sf.opencsv", name = "opencsv", version.ref = "openCsv" }
interfaces = { group = "org.incendo.interfaces", name = "interfaces-core", version.ref = "interfaces" }
adventureApi = { group = "net.kyori", name = "adventure-api", version.ref = "adventure" }
adventureTextSerializerGson = { group = "net.kyori", name = "adventure-text-serializer-gson", version.ref = "adventure" }
adventureTextSerializerPlain = { group = "net.kyori", name = "adventure-text-serializer-plain", version.ref = "adventure" }
adventureSerializerConfigurate = { group = "net.kyori", name = "adventure-serializer-configurate4", version.ref = "adventure" }
adventureTextMiniMessage = { group = "net.kyori", name = "adventure-text-minimessage", version.ref = "adventureMiniMessage" }

interfacesPaper = { group = "org.incendo.interfaces", name = "interfaces-paper", version.ref = "interfaces" }
cloudPaper = { group = "cloud.commandframework", name = "cloud-paper", version.ref = "cloud" }
cloudExtras = { group = "cloud.commandframework", name = "cloud-minecraft-extras", version.ref = "cloud" }
protocolLib = { group = "com.comphenix.protocol", name = "ProtocolLib", version.ref = "protocolLib" }

[bundles]

adventure = [ "adventureApi", "adventureTextSerializerPlain", "adventureSerializerConfigurate" ]
junit = [ "jupiterApi", "jupiterEngine" ]
