[versions]

junit = "5.7.2"
minecraft = "1.18.2"

guava = "31.0.1-jre"
checkerQual = "3.18.0"
geantyRef = "1.3.11"
configurate = "4.1.2"
openCsv = "2.3"
adventure = "4.10.0"

cloud = "1.6.2"
inventoryFramework = "0.10.4"
packetEvents = "2.0-SNAPSHOT"

[libraries]

jupiterApi = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
jupiterEngine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }

guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
checkerQual = { group = "org.checkerframework", name = "checker-qual", version.ref = "checkerQual" }
geantyRef = { group = "io.leangen.geantyref", name = "geantyref", version.ref = "geantyRef" }
configurate = { group = "org.spongepowered", name = "configurate-hocon", version.ref = "configurate" }
openCsv = { group = "net.sf.opencsv", name = "opencsv", version.ref = "openCsv" }
adventureApi = { group = "net.kyori", name = "adventure-api", version.ref = "adventure" }
adventureTextSerializerGson = { group = "net.kyori", name = "adventure-text-serializer-gson", version.ref = "adventure" }
adventureTextSerializerPlain = { group = "net.kyori", name = "adventure-text-serializer-plain", version.ref = "adventure" }
adventureSerializerConfigurate = { group = "net.kyori", name = "adventure-serializer-configurate4", version.ref = "adventure" }
adventureTextMiniMessage = { group = "net.kyori", name = "adventure-text-minimessage", version.ref = "adventure" }

cloudPaper = { group = "cloud.commandframework", name = "cloud-paper", version.ref = "cloud" }
cloudExtras = { group = "cloud.commandframework", name = "cloud-minecraft-extras", version.ref = "cloud" }
inventoryFramework = { group = "com.github.stefvanschie.inventoryframework", name = "IF", version.ref = "inventoryFramework" }
packetEvents = { group = "com.github.retrooper.packetevents", name = "spigot", version.ref = "packetEvents" }

[bundles]

adventure = [ "adventureApi", "adventureTextSerializerPlain", "adventureSerializerConfigurate" ]
junit = [ "jupiterApi", "jupiterEngine" ]
