name: "Minecommons"
description: "${project.description}"
author: "aecsocket"
version: "${project.version}"
api-version: "1.16"
main: "${project.groupId}.paper.MinecommonsPlugin"
libraries:
  - "org.spongepowered:configurate-hocon:4.1.1"
  - "cloud.commandframework:cloud-paper:${cloud.version}"
  - "cloud.commandframework:cloud-minecraft-extras:${cloud.version}"