name: "Alexandria"
description: "@description@"
main: "@group@.paper.Alexandria"
version: "@version@"
api-version: "1.19"
authors: [ "aecsocket" ]
website: "https://phosphorous.gitlab.io/alexandria"

depend: [ "KtRuntime" ]
